<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    private const UNIQUE_INDEX = 'grad_records_school_student_session_uq';

    public function up(): void
    {
        if (! Schema::hasTable('graduation_records')) {
            Schema::create('graduation_records', function (Blueprint $table) {
                $table->id();
                $table->foreignId('school_id')->constrained()->cascadeOnDelete();
                $table->foreignId('student_id')->constrained('students')->cascadeOnDelete();
                $table->foreignId('academic_session_id')->nullable()->constrained('academic_sessions')->nullOnDelete();
                $table->date('graduation_date')->nullable();
                $table->string('certificate_number')->nullable();
                $table->string('destination')->nullable();
                $table->string('status', 30)->default('graduated');
                $table->text('notes')->nullable();
                $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
                $table->timestamps();
                $table->unique(['school_id', 'student_id', 'academic_session_id'], self::UNIQUE_INDEX);
            });

            return;
        }

        // The initial deployment could create the table before MySQL rejected
        // Laravel's autogenerated long unique-index name. Complete that
        // interrupted migration safely when the table already exists.
        try {
            Schema::table('graduation_records', function (Blueprint $table) {
                $table->unique(['school_id', 'student_id', 'academic_session_id'], self::UNIQUE_INDEX);
            });
        } catch (Throwable $exception) {
            if (! str_contains($exception->getMessage(), 'Duplicate key name')) {
                throw $exception;
            }
        }
    }

    public function down(): void
    {
        if (! Schema::hasTable('graduation_records')) {
            return;
        }

        Schema::table('graduation_records', function (Blueprint $table) {
            $table->dropUnique(self::UNIQUE_INDEX);
        });
        Schema::dropIfExists('graduation_records');
    }
};
