<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\OrganizationController;
use App\Http\Controllers\Api\SchoolController;
use App\Http\Controllers\Api\AcademicSessionController;
use App\Http\Controllers\Api\TermController;
use App\Http\Controllers\Api\DivisionController;
use App\Http\Controllers\Api\ClassController;
use App\Http\Controllers\Api\StreamController;
use App\Http\Controllers\Api\StudentController;
use App\Http\Controllers\Api\ParentController;
use App\Http\Controllers\Api\SubjectController;
use App\Http\Controllers\Api\StaffController;
use App\Http\Controllers\Api\ExaminationController;
use App\Http\Controllers\Api\ExamScoreController;
use App\Http\Controllers\Api\AttendanceController;
use App\Http\Controllers\Api\FeeCategoryController;
use App\Http\Controllers\Api\StudentFeeController;
use App\Http\Controllers\Api\FeePaymentController;
use App\Http\Controllers\Api\PaymentReceiptController;
use App\Http\Controllers\Api\StudentEnrollmentController;
use App\Http\Controllers\Api\ParentStudentController;
use App\Http\Controllers\Api\StudentPromotionController;
use App\Http\Controllers\Api\ResultController;
use App\Http\Controllers\Api\TimetableController;
use App\Http\Controllers\Api\ReportCardController;
use App\Http\Controllers\Api\FeeController;
use App\Http\Controllers\Api\SubscriptionPlanController;
use App\Http\Controllers\Api\SchoolSubscriptionController;
use App\Http\Controllers\Api\SystemSettingController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\ReceiptController;
use App\Http\Controllers\Api\AdminRevenueController;
use App\Http\Controllers\Api\ParentDashboardController;
use App\Http\Controllers\Api\TeacherDashboardController;
use App\Http\Controllers\Api\ResultEntryController;
use App\Http\Controllers\Api\PromoCampaignController;
use App\Http\Controllers\Api\CurrencyController;
use App\Http\Controllers\Api\CouponController;
use App\Http\Controllers\Api\BookController;
use App\Http\Controllers\Api\BookLoanController;
use App\Http\Controllers\Api\HostelController;
use App\Http\Controllers\Api\HostelRoomController;
use App\Http\Controllers\Api\HostelAllocationController;
use App\Http\Controllers\Api\ExpenseController;
use App\Http\Controllers\Api\MedicalRecordController;
use App\Http\Controllers\Api\ClinicVisitController;
use App\Http\Controllers\Api\VehicleController;
use App\Http\Controllers\Api\TransportRouteController;
use App\Http\Controllers\Api\TransportAllocationController;
use App\Http\Controllers\Api\VisitorController;
use App\Http\Controllers\Api\StudentGatePassController;
use App\Http\Controllers\Api\ReceptionAppointmentController;
use App\Http\Controllers\Api\TeacherPortalController;
use App\Http\Controllers\Api\FormTeacherPortalController;
use App\Http\Controllers\Api\PlatformOwnerController;
use App\Http\Controllers\Api\OrganizationOwnerController;
use App\Http\Controllers\Api\ProprietorController;
use App\Http\Controllers\Api\PrincipalController;
use App\Http\Controllers\Api\VicePrincipalAcademicController;
use App\Http\Controllers\Api\VicePrincipalAdminController;
use App\Http\Controllers\Api\NurseryHeadController;
use App\Http\Controllers\Api\PrimaryHeadmasterController;
use App\Http\Controllers\Api\SecondaryPrincipalController;
use App\Http\Controllers\Api\StudentPortalController;
use App\Http\Controllers\Api\ParentPortalController;
use App\Http\Controllers\Api\RoleInvitationController;
use App\Http\Controllers\Api\ActivityLogController;
use App\Http\Controllers\Api\SchoolSetupDelegationController;
use App\Http\Controllers\Api\SchoolSetupController;

Route::prefix('v1')->group(function () {
    Route::post('payments/paystack/webhook', [PaymentController::class, 'webhook']);
    Route::get('payments/paystack/verify/{reference}', [PaymentController::class, 'verify']);
    Route::get('/countries', [SchoolController::class, 'countries']);
    Route::get('/roles', [\App\Http\Controllers\Api\RoleController::class, 'index'])->middleware('auth:sanctum');
    Route::get('role-invitations/preview/{token}', [RoleInvitationController::class, 'preview']);
    Route::post('role-invitations/accept', [RoleInvitationController::class, 'accept']);
    Route::post('/register', [AuthController::class, 'register']);
    Route::post('/login', [AuthController::class, 'login']);

    Route::middleware('auth:sanctum')->group(function () {
        Route::get('/me/context', [AuthController::class, 'context']);
        Route::post('/me/switch-school', [AuthController::class, 'switchSchool']);
        Route::post('/logout', [AuthController::class, 'logout']);
        Route::get('/dashboard', [DashboardController::class, 'index']);
        Route::get('/org-owner/dashboard', [OrganizationOwnerController::class, 'dashboard']);
        Route::get('/activity-logs', [ActivityLogController::class, 'index']);
        Route::post('role-invitations/accept-authenticated', [RoleInvitationController::class, 'acceptAuthenticated']);
        Route::apiResource('role-invitations', RoleInvitationController::class)->except(['show', 'update']);
        Route::post('role-invitations/{roleInvitation}/revoke', [RoleInvitationController::class, 'revoke']);

        Route::middleware('role:super_admin')->group(function () {
            Route::get('system-settings', [SystemSettingController::class, 'index']);
            Route::put('system-settings', [SystemSettingController::class, 'update']);
            Route::apiResource('subscription-plans', SubscriptionPlanController::class)->except(['index', 'show']);
            Route::apiResource('school-subscriptions', SchoolSubscriptionController::class);
            Route::apiResource('coupons', CouponController::class);
            Route::apiResource('promo-campaigns', PromoCampaignController::class);
            Route::get('admin/revenue-dashboard', [AdminRevenueController::class, 'index']);
            Route::get('platform-owner/dashboard', [PlatformOwnerController::class, 'dashboard']);
        });

        Route::get('subscription-plans', [SubscriptionPlanController::class, 'index']);
        Route::get('subscription-plans/{subscriptionPlan}', [SubscriptionPlanController::class, 'show']);
        Route::apiResource('organizations', OrganizationController::class);
        Route::apiResource('schools', SchoolController::class);
        Route::get('my-subscription', [SchoolSubscriptionController::class, 'mySubscription']);
        Route::apiResource('currencies', CurrencyController::class);

        Route::middleware(['has.school', 'role:proprietor'])->prefix('school-setup')->group(function () {
            Route::get('progress', [SchoolSetupController::class, 'progress']);
            Route::get('delegations', [SchoolSetupDelegationController::class, 'index']);
            Route::put('delegations/{user}', [SchoolSetupDelegationController::class, 'update']);
            Route::delete('delegations/{user}', [SchoolSetupDelegationController::class, 'destroy']);
        });

        Route::middleware(['has.school', 'subscription'])->group(function () {
            Route::get('school-settings', [\App\Http\Controllers\Api\SchoolSettingController::class, 'show']);
            Route::put('school-settings', [\App\Http\Controllers\Api\SchoolSettingController::class, 'update']);
            Route::get('proprietor/dashboard', [ProprietorController::class, 'dashboard']);
            Route::get('principal/dashboard', [PrincipalController::class, 'dashboard']);
            Route::get('vp-academic/dashboard', [VicePrincipalAcademicController::class, 'dashboard']);
            Route::get('vp-admin/dashboard', [VicePrincipalAdminController::class, 'dashboard']);
            Route::get('teacher/dashboard', [TeacherPortalController::class, 'dashboard']);
            Route::get('form-teacher/dashboard', [FormTeacherPortalController::class, 'dashboard']);
            Route::get('nursery-head/dashboard', [NurseryHeadController::class, 'dashboard']);
            Route::get('primary-head/dashboard', [PrimaryHeadmasterController::class, 'dashboard']);
            Route::get('secondary-head/dashboard', [SecondaryPrincipalController::class, 'dashboard']);
            Route::get('student/dashboard', [StudentPortalController::class, 'dashboard']);
            Route::get('parent/dashboard', [ParentPortalController::class, 'dashboard']);
            Route::middleware('permission:manage_academic_sessions')->apiResource('academic-sessions', AcademicSessionController::class);
            Route::middleware('permission:manage_terms')->apiResource('terms', TermController::class);
            Route::middleware('permission:manage_divisions')->apiResource('divisions', DivisionController::class);
            Route::middleware('permission:manage_classes')->apiResource('classes', ClassController::class);
            Route::middleware('permission:manage_streams')->apiResource('streams', StreamController::class);
            Route::middleware('permission:manage_subjects')->apiResource('subjects', SubjectController::class);
            Route::apiResource('staff', StaffController::class);
            Route::middleware('permission:manage_students')->apiResource('students', StudentController::class);
            Route::middleware('permission:manage_fee_categories')->apiResource('fees', FeeController::class);
            Route::apiResource('enrollments', StudentEnrollmentController::class);
            Route::apiResource('fee-payments', FeePaymentController::class)->only(['index', 'store', 'show', 'destroy']);
            Route::apiResource('payment-receipts', PaymentReceiptController::class)->only(['index', 'show']);
            Route::apiResource('promotions', StudentPromotionController::class);
            Route::get('attendance', [AttendanceController::class, 'index']);
            Route::post('attendance/bulk', [AttendanceController::class, 'bulkStore']);
            Route::get('results', [ResultController::class, 'index']);
            Route::post('results/{result}/publish', [ResultController::class, 'publish']);
            Route::get('report-cards', [ReportCardController::class, 'index']);
            Route::get('report-cards/{reportCard}/download', [ReportCardController::class, 'downloadPdf']);
            Route::prefix('result-entry')->group(function () {
                Route::get('/students', [ResultEntryController::class, 'students']);
                Route::post('/save', [ResultEntryController::class, 'save']);
            });
            Route::apiResource('examinations', ExaminationController::class);
            Route::apiResource('exam-scores', ExamScoreController::class);
            Route::apiResource('timetables', TimetableController::class);
            Route::apiResource('books', BookController::class);
            Route::apiResource('book-loans', BookLoanController::class);
            Route::apiResource('hostels', HostelController::class);
            Route::apiResource('hostel-rooms', HostelRoomController::class);
            Route::apiResource('hostel-allocations', HostelAllocationController::class);
            Route::apiResource('expenses', ExpenseController::class);
            Route::apiResource('medical-records', MedicalRecordController::class);
            Route::apiResource('clinic-visits', ClinicVisitController::class);
            Route::apiResource('vehicles', VehicleController::class);
            Route::apiResource('transport-routes', TransportRouteController::class);
            Route::apiResource('transport-allocations', TransportAllocationController::class);
            Route::apiResource('visitors', VisitorController::class);
            Route::apiResource('gate-passes', StudentGatePassController::class);
            Route::apiResource('appointments', ReceptionAppointmentController::class);
        });
    });
});
