<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\OrganizationController;
use App\Http\Controllers\Api\SchoolController;
use App\Http\Controllers\Api\SchoolBrandingController;
use App\Http\Controllers\Api\AcademicSessionController;
use App\Http\Controllers\Api\TermController;
use App\Http\Controllers\Api\DivisionController;
use App\Http\Controllers\Api\ClassController;
use App\Http\Controllers\Api\StreamController;
use App\Http\Controllers\Api\StudentController;
use App\Http\Controllers\Api\ParentController;
use App\Http\Controllers\Api\SubjectController;
use App\Http\Controllers\Api\StaffController;
use App\Http\Controllers\Api\ExaminationController;
use App\Http\Controllers\Api\ExamScoreController;
use App\Http\Controllers\Api\AttendanceController;
use App\Http\Controllers\Api\FeeCategoryController;
use App\Http\Controllers\Api\StudentFeeController;
use App\Http\Controllers\Api\FeePaymentController;
use App\Http\Controllers\Api\PaymentReceiptController;
use App\Http\Controllers\Api\StudentEnrollmentController;
use App\Http\Controllers\Api\ParentStudentController;
use App\Http\Controllers\Api\StudentPromotionController;
use App\Http\Controllers\Api\ResultController;
use App\Http\Controllers\Api\ResultSubmissionController;
use App\Http\Controllers\Api\AssessmentStructureController;
use App\Http\Controllers\Api\TimetableController;
use App\Http\Controllers\Api\ReportCardController;
use App\Http\Controllers\Api\FeeController;
use App\Http\Controllers\Api\SubscriptionPlanController;
use App\Http\Controllers\Api\SchoolSubscriptionController;
use App\Http\Controllers\Api\SystemSettingController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\ReceiptController;
use App\Http\Controllers\Api\AdminRevenueController;
use App\Http\Controllers\Api\ParentDashboardController;
use App\Http\Controllers\Api\TeacherDashboardController;
use App\Http\Controllers\Api\ResultEntryController;
use App\Http\Controllers\Api\PromoCampaignController;
use App\Http\Controllers\Api\CurrencyController;
use App\Http\Controllers\Api\CouponController;
use App\Http\Controllers\Api\BookController;
use App\Http\Controllers\Api\BookLoanController;
use App\Http\Controllers\Api\HostelController;
use App\Http\Controllers\Api\HostelRoomController;
use App\Http\Controllers\Api\HostelAllocationController;
use App\Http\Controllers\Api\ExpenseController;
use App\Http\Controllers\Api\MedicalRecordController;
use App\Http\Controllers\Api\ClinicVisitController;
use App\Http\Controllers\Api\VehicleController;
use App\Http\Controllers\Api\TransportRouteController;
use App\Http\Controllers\Api\TransportAllocationController;
use App\Http\Controllers\Api\VisitorController;
use App\Http\Controllers\Api\StudentGatePassController;
use App\Http\Controllers\Api\ReceptionAppointmentController;
use App\Http\Controllers\Api\TeacherPortalController;
use App\Http\Controllers\Api\FormTeacherPortalController;
use App\Http\Controllers\Api\PlatformOwnerController;
use App\Http\Controllers\Api\OrganizationOwnerController;
use App\Http\Controllers\Api\ProprietorController;
use App\Http\Controllers\Api\PrincipalController;
use App\Http\Controllers\Api\VicePrincipalAcademicController;
use App\Http\Controllers\Api\VicePrincipalAdminController;
use App\Http\Controllers\Api\NurseryHeadController;
use App\Http\Controllers\Api\PrimaryHeadmasterController;
use App\Http\Controllers\Api\SecondaryPrincipalController;
use App\Http\Controllers\Api\StudentPortalController;
use App\Http\Controllers\Api\ParentPortalController;
use App\Http\Controllers\Api\RoleInvitationController;
use App\Http\Controllers\Api\PortalAccountController;
use App\Http\Controllers\Api\EmailVerificationController;
use App\Http\Controllers\Api\PasswordResetController;
use App\Http\Controllers\Api\PlatformAnnouncementController;
use App\Http\Controllers\Api\LocalEmailController;
use App\Http\Controllers\Api\ActivityLogController;
use App\Http\Controllers\Api\SchoolSetupDelegationController;
use App\Http\Controllers\Api\SchoolSetupController;
use App\Http\Controllers\Api\AdmissionController;
use App\Http\Controllers\Api\SchoolEventController;
use App\Http\Controllers\Api\SchoolFacilityController;
use App\Http\Controllers\Api\AssignmentController;
use App\Http\Controllers\Api\CommunicationController;
use App\Http\Controllers\Api\CbtQuestionController;
use App\Http\Controllers\Api\CbtAssessmentController;
use App\Http\Controllers\Api\StudentLeaveApplicationController;
use App\Http\Controllers\Api\AssessmentActivityController;
use App\Http\Controllers\Api\PlatformOperationsController;
use App\Http\Controllers\Api\PayrollEntryController;
use App\Http\Controllers\Api\FinancialReportController;
use App\Http\Controllers\Api\LibraryController;
use App\Http\Controllers\Api\ReceptionActivityController;
use App\Http\Controllers\Api\TransportLogController;
use App\Http\Controllers\Api\FeeAdjustmentController;
use App\Http\Controllers\Api\FeatureController;
use App\Http\Controllers\Api\GraduationRecordController;

Route::prefix('v1')->group(function () {
    Route::post('payments/paystack/webhook', [PaymentController::class, 'webhook']);

    Route::get('/countries', [SchoolController::class, 'countries']);
    Route::get('/roles', [\App\Http\Controllers\Api\RoleController::class, 'index'])->middleware('auth:sanctum');
    Route::get('role-invitations/preview/{token}', [RoleInvitationController::class, 'preview']);
    Route::post('role-invitations/accept', [RoleInvitationController::class, 'accept']);
    Route::post('/register', [AuthController::class, 'register'])->middleware('throttle:auth');
    Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:auth');
    Route::get('email/verify/{id}/{hash}', [EmailVerificationController::class, 'verify'])->middleware('signed:relative')->name('verification.verify');
    Route::post('email/resend-verification', [EmailVerificationController::class, 'resend'])->middleware('throttle:auth');
    Route::post('forgot-password', [PasswordResetController::class, 'sendLink'])->middleware('throttle:auth');
    Route::post('reset-password', [PasswordResetController::class, 'reset'])->middleware('throttle:auth');

    Route::middleware(['auth:sanctum', 'throttle:api', 'idempotency'])->group(function () {
        Route::get('/me/context', [AuthController::class, 'context']);
        Route::post('/me/profile', [AuthController::class, 'profile']);
        Route::put('/me/change-password', [AuthController::class, 'changePassword']);
        Route::get('/me/staff-profile', [AuthController::class, 'staffProfile']);
        Route::put('/me/staff-profile', [AuthController::class, 'updateStaffProfile']);
        Route::post('/me/switch-school', [AuthController::class, 'switchSchool']);
        Route::post('/logout', [AuthController::class, 'logout']);
        Route::get('/dashboard', [DashboardController::class, 'index']);
        Route::get('/org-owner/dashboard', [OrganizationOwnerController::class, 'dashboard']);
        Route::get('/org-owner/workspace', [OrganizationOwnerController::class, 'workspace']);
        Route::get('/activity-logs', [ActivityLogController::class, 'index']);
        Route::post('role-invitations/accept-authenticated', [RoleInvitationController::class, 'acceptAuthenticated']);
        Route::middleware(['has.school', 'role:proprietor'])->apiResource('role-invitations', RoleInvitationController::class)->except(['show', 'update']);
        Route::middleware(['has.school', 'role:proprietor'])->post('role-invitations/{roleInvitation}/revoke', [RoleInvitationController::class, 'revoke']);

        Route::middleware('role:super_admin')->group(function () {
            Route::get('system-settings', [SystemSettingController::class, 'index']);
            Route::put('system-settings', [SystemSettingController::class, 'update']);
            Route::apiResource('subscription-plans', SubscriptionPlanController::class)->except(['index', 'show']);
            Route::apiResource('school-subscriptions', SchoolSubscriptionController::class);
            Route::post('schools/{school}/toggle-exemption', [SchoolController::class, 'toggleExemption']);
            Route::post('schools/{school}/extend-trial', [SchoolController::class, 'extendTrial']);
            Route::post('schools/{school}/subscription-status', [SchoolController::class, 'updateSubscriptionStatus']);
            Route::post('schools/{school}/grant-custom-timeframe', [SchoolController::class, 'grantCustomTimeframe']);
            Route::post('schools/{school}/set-discount', [SchoolController::class, 'setDiscount']);
            Route::apiResource('coupons', CouponController::class);
            Route::apiResource('promo-campaigns', PromoCampaignController::class);
            Route::apiResource('currencies', CurrencyController::class);
            Route::apiResource('features', FeatureController::class);
            Route::get('platform-announcements', [PlatformAnnouncementController::class, 'index']);
            Route::post('platform-announcements/preview-recipients', [PlatformAnnouncementController::class, 'previewRecipients']);
            Route::post('platform-announcements', [PlatformAnnouncementController::class, 'store']);
            Route::put('platform-announcements/{platformAnnouncement}', [PlatformAnnouncementController::class, 'update']);
            Route::delete('platform-announcements/{platformAnnouncement}', [PlatformAnnouncementController::class, 'destroy']);
            Route::post('platform-announcements/{platformAnnouncement}/send', [PlatformAnnouncementController::class, 'send']);
            Route::get('platform-email/status', [PlatformAnnouncementController::class, 'emailStatus']);
            Route::post('platform-email/test', [PlatformAnnouncementController::class, 'testEmail']);
            Route::get('local-email-messages', [LocalEmailController::class, 'index']);
            Route::get('local-email-messages/{localEmailMessage}', [LocalEmailController::class, 'show']);
            Route::post('local-email-messages/{localEmailMessage}/read', [LocalEmailController::class, 'markRead']);
            Route::delete('local-email-messages', [LocalEmailController::class, 'clear']);
            Route::get('admin/revenue-dashboard', [AdminRevenueController::class, 'index']);
            Route::get('platform-owner/dashboard', [PlatformOwnerController::class, 'dashboard']);
            Route::get('platform/system-health', [PlatformOperationsController::class, 'health']);
        });

        Route::get('subscription-plans', [SubscriptionPlanController::class, 'index']);
        Route::get('subscription-plans/{subscriptionPlan}', [SubscriptionPlanController::class, 'show']);
        Route::apiResource('organizations', OrganizationController::class)->except(['store']);
        Route::middleware('role:super_admin')->post('organizations', [OrganizationController::class, 'store']);
        Route::apiResource('schools', SchoolController::class);
        Route::get('my-subscription', [SchoolSubscriptionController::class, 'mySubscription']);
        Route::middleware('role:proprietor')->post('payments/initialize-subscription', [PaymentController::class, 'initializeSubscription']);
        Route::middleware('role:proprietor')->get('payments/verify-subscription/{reference}', [PaymentController::class, 'verifySubscription']);

        Route::middleware(['has.school', 'role:proprietor'])->prefix('school-setup')->group(function () {
            Route::get('progress', [SchoolSetupController::class, 'progress']);
            Route::get('delegations', [SchoolSetupDelegationController::class, 'index']);
            Route::put('delegations/{user}', [SchoolSetupDelegationController::class, 'update']);
            Route::delete('delegations/{user}', [SchoolSetupDelegationController::class, 'destroy']);
        });

        Route::middleware(['has.school', 'password.changed', 'staff.active', 'subscription'])->group(function () {
            Route::post('payments/paystack/initialize', [PaymentController::class, 'initialize']);
            Route::get('payments/paystack/verify/{reference}', [PaymentController::class, 'verify']);
            Route::get('school-settings', [\App\Http\Controllers\Api\SchoolSettingController::class, 'show']);
            Route::put('school-settings', [\App\Http\Controllers\Api\SchoolSettingController::class, 'update']);
            Route::get('school-branding', [SchoolBrandingController::class, 'show']);
            Route::post('school-branding', [SchoolBrandingController::class, 'update']);
            Route::get('proprietor/dashboard', [ProprietorController::class, 'dashboard']);
            Route::middleware('role:principal')->get('principal/dashboard', [PrincipalController::class, 'dashboard']);
            Route::get('vp-academic/dashboard', [VicePrincipalAcademicController::class, 'dashboard']);
            Route::get('vp-admin/dashboard', [VicePrincipalAdminController::class, 'dashboard']);
            Route::get('teacher/dashboard', [TeacherPortalController::class, 'dashboard']);
            Route::get('form-teacher/dashboard', [FormTeacherPortalController::class, 'dashboard']);
            Route::get('nursery-head/dashboard', [NurseryHeadController::class, 'dashboard']);
            Route::get('primary-head/dashboard', [PrimaryHeadmasterController::class, 'dashboard']);
            Route::get('secondary-head/dashboard', [SecondaryPrincipalController::class, 'dashboard']);
            Route::get('student/dashboard', [StudentPortalController::class, 'dashboard']);
            Route::middleware('permission:portal_student_access')->get('student/library', [LibraryController::class, 'studentLibrary']);
            Route::get('student/report-card/download', [StudentPortalController::class, 'downloadLatestReportCard']);
            Route::get('parent/dashboard', [ParentPortalController::class, 'dashboard']);
            Route::get('parent/report-cards/{student}/download', [ParentPortalController::class, 'downloadReportCard']);
            Route::middleware('permission:view_students')->get('academic-sessions', [AcademicSessionController::class, 'index']);
            Route::middleware('permission:manage_academic_sessions')->apiResource('academic-sessions', AcademicSessionController::class)->except(['index']);
            Route::middleware('permission:view_students')->get('terms', [TermController::class, 'index']);
            Route::middleware('permission:manage_terms')->apiResource('terms', TermController::class)->except(['index']);
            Route::middleware('permission:view_students')->get('divisions', [DivisionController::class, 'index']);
            Route::middleware('permission:manage_divisions')->apiResource('divisions', DivisionController::class)->except(['index']);
            Route::middleware('permission:view_students')->get('classes', [ClassController::class, 'index']);
            Route::middleware('permission:manage_classes')->apiResource('classes', ClassController::class)->except(['index']);
            Route::middleware('permission:view_students')->get('streams', [StreamController::class, 'index']);
            Route::middleware('permission:manage_streams')->apiResource('streams', StreamController::class)->except(['index']);
            Route::middleware('permission:view_students')->get('subjects', [SubjectController::class, 'index']);
            Route::middleware('permission:manage_subjects')->apiResource('subjects', SubjectController::class)->except(['index']);
            Route::middleware('permission:view_staff')->get('staff', [StaffController::class, 'index']);
            Route::middleware('permission:view_staff')->get('staff/{staff}', [StaffController::class, 'show']);
            Route::middleware(['role:proprietor', 'permission:manage_staff'])->post('staff', [StaffController::class, 'store']);
            Route::middleware(['role:proprietor', 'permission:manage_staff'])->put('staff/{staff}', [StaffController::class, 'update']);
            Route::middleware(['role:proprietor', 'permission:manage_staff'])->patch('staff/{staff}', [StaffController::class, 'update']);
            Route::middleware(['role:proprietor', 'permission:manage_staff'])->delete('staff/{staff}', [StaffController::class, 'destroy']);
            Route::middleware('permission:view_students')->get('students', [StudentController::class, 'index']);
            Route::middleware('permission:view_students')->get('students/{student}', [StudentController::class, 'show']);
            Route::middleware('permission:manage_students')->post('students', [StudentController::class, 'store']);
            Route::middleware('permission:manage_students')->put('students/{student}', [StudentController::class, 'update']);
            Route::middleware('permission:manage_students')->patch('students/{student}', [StudentController::class, 'update']);
            Route::middleware('permission:manage_students')->delete('students/{student}', [StudentController::class, 'destroy']);
            Route::middleware('permission:manage_students')->post('students/{student}/portal-account', [PortalAccountController::class, 'linkStudent']);
            Route::middleware('permission:view_students')->get('parents', [ParentController::class, 'index']);
            Route::middleware('permission:view_students')->get('parents/{parent}', [ParentController::class, 'show']);
            Route::middleware('permission:manage_students')->post('parents', [ParentController::class, 'store']);
            Route::middleware('permission:manage_students')->put('parents/{parent}', [ParentController::class, 'update']);
            Route::middleware('permission:manage_students')->patch('parents/{parent}', [ParentController::class, 'update']);
            Route::middleware('permission:manage_students')->delete('parents/{parent}', [ParentController::class, 'destroy']);
            Route::middleware('permission:manage_students')->post('parents/{parent}/portal-account', [PortalAccountController::class, 'linkParent']);
            Route::middleware('permission:view_finance_reports')->get('fees', [FeeController::class, 'index']);
            Route::middleware(['role:proprietor', 'permission:manage_fee_categories'])->apiResource('fees', FeeController::class)->except(['index']);
            Route::middleware('permission:view_finance_reports')->get('student-fees', [StudentFeeController::class, 'index']);
            Route::middleware('permission:manage_student_fees')->apiResource('student-fees', StudentFeeController::class)->except(['index']);
            Route::middleware('permission:manage_students')->apiResource('enrollments', StudentEnrollmentController::class);
            Route::middleware('permission:approve_admissions')->post('admissions', [AdmissionController::class, 'store']);
            Route::middleware('permission:view_finance_reports')->apiResource('fee-payments', FeePaymentController::class)->only(['index', 'show']);
            Route::middleware('permission:receive_payments')->apiResource('fee-payments', FeePaymentController::class)->only(['store', 'destroy']);
            Route::middleware('permission:view_finance_reports')->get('fee-adjustments/discounts', [FeeAdjustmentController::class, 'discounts']);
            Route::middleware('permission:manage_student_fees')->put('student-fees/{studentFee}/discount', [FeeAdjustmentController::class, 'applyDiscount']);
            Route::middleware('permission:receive_payments')->post('fee-payments/{feePayment}/reverse', [FeeAdjustmentController::class, 'reversePayment']);
            Route::middleware('permission:view_finance_reports')->apiResource('payment-receipts', PaymentReceiptController::class)->only(['index', 'show']);
            Route::middleware('permission:manage_promotions')->apiResource('promotions', StudentPromotionController::class);
            Route::middleware('permission:manage_promotions')->apiResource('graduation-records', GraduationRecordController::class);
            Route::middleware('permission:view_students')->get('attendance', [AttendanceController::class, 'index']);
            Route::middleware('permission:view_students')->get('attendance/class-list', [AttendanceController::class, 'classList']);
            Route::middleware('permission:manage_attendance')->post('attendance/bulk', [AttendanceController::class, 'bulkStore']);
            Route::middleware('permission:view_results')->get('results', [ResultController::class, 'index']);
            Route::middleware(['role:proprietor', 'permission:manage_assessments'])->apiResource('assessment-structures', AssessmentStructureController::class);
            Route::middleware('permission:approve_results')->post('results/{result}/publish', [ResultController::class, 'publish']);
            Route::middleware('permission:view_results')->get('report-cards', [ReportCardController::class, 'index']);
            Route::middleware('permission:view_results')->get('report-cards/{reportCard}/download', [ReportCardController::class, 'downloadPdf']);
            Route::middleware('permission:manage_exam_scores')->prefix('result-entry')->group(function () {
                Route::get('/students', [ResultEntryController::class, 'students']);
                Route::post('/save', [ResultEntryController::class, 'save']);
            });
            Route::middleware('permission:view_results')->get('result-submissions', [ResultSubmissionController::class, 'index']);
            Route::middleware('permission:manage_exam_scores')->post('result-submissions', [ResultSubmissionController::class, 'createSubmission']);
            Route::middleware('permission:manage_exam_scores')->post('result-submissions/{submission}/autosave', [ResultSubmissionController::class, 'autoSave']);
            Route::middleware('permission:manage_exam_scores')->post('result-submissions/{submission}/submit', [ResultSubmissionController::class, 'submit']);
            Route::middleware('permission:approve_results')->post('result-submissions/{submission}/approve', [ResultSubmissionController::class, 'approve']);
            Route::middleware('permission:approve_results')->post('result-submissions/{submission}/publish', [ResultSubmissionController::class, 'publish']);
            Route::middleware('permission:manage_exam_scores')->post('result-submissions/{submission}/reopen', [ResultSubmissionController::class, 'reopen']);
            Route::middleware('permission:view_results')->get('examinations', [ExaminationController::class, 'index']);
            Route::middleware('permission:manage_examinations')->apiResource('examinations', ExaminationController::class)->except(['index']);
            Route::middleware('permission:manage_exam_scores')->apiResource('exam-scores', ExamScoreController::class);
            Route::middleware('permission:view_timetable')->apiResource('timetables', TimetableController::class)->only(['index', 'show']);
            Route::middleware('permission:view_assignments')->get('assignments', [AssignmentController::class, 'index']);
            Route::middleware('permission:manage_assignments')->post('assignments', [AssignmentController::class, 'store']);
            Route::middleware('permission:manage_assignments')->put('assignments/{assignment}', [AssignmentController::class, 'update']);
            Route::middleware('permission:manage_assignments')->delete('assignments/{assignment}', [AssignmentController::class, 'destroy']);
            Route::middleware('permission:portal_student_access')->get('student/assignments', [AssignmentController::class, 'studentAssignments']);
            Route::middleware('permission:portal_student_access')->post('assignments/{assignment}/submit', [AssignmentController::class, 'studentSubmit']);
            Route::middleware('permission:portal_student_access')->get('assignments/{assignment}/my-submission', [AssignmentController::class, 'mySubmission']);
            Route::middleware('permission:manage_assignments')->get('assignments/{assignment}/submissions', [AssignmentController::class, 'submissions']);
            Route::middleware('permission:manage_assignments')->post('assignments/{assignment}/submissions/{submission}/review', [AssignmentController::class, 'teacherReview']);
            Route::middleware('permission:manage_timetable')->apiResource('timetables', TimetableController::class)->except(['index', 'show']);
            Route::middleware('permission:manage_library')->get('library/workspace', [LibraryController::class, 'workspace']);
            Route::middleware('permission:manage_library')->apiResource('books', BookController::class);
            Route::middleware('permission:manage_library')->apiResource('book-loans', BookLoanController::class);
            Route::middleware('permission:manage_hostel')->apiResource('hostels', HostelController::class);
            Route::middleware('permission:manage_hostel')->apiResource('hostel-rooms', HostelRoomController::class);
            Route::middleware('permission:manage_hostel')->apiResource('hostel-allocations', HostelAllocationController::class);
            Route::middleware('permission:view_finance_reports')->get('expenses', [ExpenseController::class, 'index']);
            Route::middleware('permission:manage_budget')->apiResource('expenses', ExpenseController::class)->except(['index', 'show']);
            Route::middleware('permission:view_finance_reports')->get('expenses/{expense}', [ExpenseController::class, 'show']);
            Route::middleware('permission:manage_clinic')->apiResource('medical-records', MedicalRecordController::class);
            Route::middleware('permission:manage_clinic')->apiResource('clinic-visits', ClinicVisitController::class);
            Route::middleware('permission:manage_transport')->apiResource('vehicles', VehicleController::class);
            Route::middleware('permission:manage_transport')->apiResource('transport-routes', TransportRouteController::class);
            Route::middleware('permission:manage_transport')->apiResource('transport-allocations', TransportAllocationController::class);
            Route::middleware('permission:manage_transport')->apiResource('transport-logs', TransportLogController::class);
            Route::middleware('permission:manage_front_desk')->apiResource('visitors', VisitorController::class);
            Route::middleware('permission:manage_front_desk')->apiResource('gate-passes', StudentGatePassController::class);
            Route::middleware('permission:manage_front_desk')->apiResource('appointments', ReceptionAppointmentController::class);
            Route::middleware('permission:manage_front_desk')->get('reception-activities', [ReceptionActivityController::class, 'index']);
            Route::middleware('permission:manage_front_desk')->post('reception-activities', [ReceptionActivityController::class, 'store']);
            Route::middleware('permission:manage_front_desk')->put('reception-activities/{receptionActivity}', [ReceptionActivityController::class, 'update']);
            Route::middleware('permission:manage_front_desk')->delete('reception-activities/{receptionActivity}', [ReceptionActivityController::class, 'destroy']);
            Route::middleware('permission:manage_events')->get('school-events/options', [SchoolEventController::class, 'options']);
            Route::middleware('permission:manage_events')->apiResource('school-events', SchoolEventController::class);
            Route::middleware('permission:manage_facilities')->get('school-facilities/options', [SchoolFacilityController::class, 'options']);
            Route::middleware('permission:manage_facilities')->apiResource('school-facilities', SchoolFacilityController::class);
            Route::middleware('permission:view_communication')->get('communications', [CommunicationController::class, 'index']);
            Route::middleware('permission:view_communication')->get('communications/{communication}', [CommunicationController::class, 'show']);
            Route::middleware('permission:send_communication')->post('communications', [CommunicationController::class, 'store']);
            Route::middleware('permission:send_communication')->put('communications/{communication}', [CommunicationController::class, 'update']);
            Route::middleware('permission:send_communication')->delete('communications/{communication}', [CommunicationController::class, 'destroy']);
            Route::middleware('permission:view_communication')->post('communications/{communication}/read', [CommunicationController::class, 'markRead']);
            Route::middleware('permission:portal_parent_access')->get('portal/transport-tracking', [TransportAllocationController::class, 'tracking']);
            Route::middleware('permission:portal_student_access')->get('student/transport-tracking', [TransportAllocationController::class, 'tracking']);
            Route::middleware('permission:portal_parent_access')->get('portal/leave-applications', [StudentLeaveApplicationController::class, 'index']);
            Route::middleware('permission:portal_parent_access')->post('portal/leave-applications', [StudentLeaveApplicationController::class, 'store']);
            Route::middleware('permission:portal_student_access')->get('student/leave-applications', [StudentLeaveApplicationController::class, 'index']);
            Route::middleware('permission:portal_student_access')->post('student/leave-applications', [StudentLeaveApplicationController::class, 'store']);
            Route::middleware('permission:manage_students')->post('student-leave-applications/{studentLeaveApplication}/review', [StudentLeaveApplicationController::class, 'review']);
            Route::middleware('permission:view_cbt_questions')->get('assessment-activities', [AssessmentActivityController::class, 'index']);
            Route::middleware('permission:manage_examinations')->post('assessment-activities', [AssessmentActivityController::class, 'store']);
            Route::middleware('permission:manage_examinations')->put('assessment-activities/{assessmentActivity}', [AssessmentActivityController::class, 'update']);
            Route::middleware('permission:manage_examinations')->delete('assessment-activities/{assessmentActivity}', [AssessmentActivityController::class, 'destroy']);
            Route::middleware('permission:view_finance_reports')->get('payroll', [PayrollEntryController::class, 'index']);
            Route::middleware('permission:view_finance_reports')->get('financial-reports', [FinancialReportController::class, 'index']);
            Route::middleware('permission:manage_payroll')->post('payroll', [PayrollEntryController::class, 'store']);
            Route::middleware('permission:manage_payroll')->put('payroll/{payrollEntry}', [PayrollEntryController::class, 'update']);
            Route::middleware('permission:manage_payroll')->delete('payroll/{payrollEntry}', [PayrollEntryController::class, 'destroy']);
            Route::middleware('permission:view_cbt_questions')->get('cbt-questions', [CbtQuestionController::class, 'index']);
            Route::middleware('permission:manage_cbt_questions')->post('cbt-questions', [CbtQuestionController::class, 'store']);
            Route::middleware('permission:manage_cbt_questions')->post('cbt-questions/bulk', [CbtQuestionController::class, 'bulkStore']);
            Route::middleware('permission:manage_cbt_questions')->put('cbt-questions/{cbtQuestion}', [CbtQuestionController::class, 'update']);
            Route::middleware('permission:manage_cbt_questions')->post('cbt-questions/{cbtQuestion}/review', [CbtQuestionController::class, 'review']);
            Route::middleware('permission:manage_cbt_questions')->delete('cbt-questions/{cbtQuestion}', [CbtQuestionController::class, 'destroy']);
            Route::middleware('permission:view_cbt_questions')->get('cbt-assessments', [CbtAssessmentController::class, 'index']);
            Route::middleware('permission:manage_cbt_questions')->post('cbt-assessments', [CbtAssessmentController::class, 'store']);
            Route::middleware('permission:view_cbt_questions')->get('cbt-assessments/{cbtAssessment}', [CbtAssessmentController::class, 'show']);
            Route::middleware('permission:manage_cbt_questions')->post('cbt-assessments/{cbtAssessment}/publish', [CbtAssessmentController::class, 'publish']);
            Route::middleware('permission:manage_cbt_questions')->post('cbt-assessments/{cbtAssessment}/close', [CbtAssessmentController::class, 'close']);
            Route::middleware('permission:view_cbt_questions')->get('cbt-assessments/{cbtAssessment}/attempts', [CbtAssessmentController::class, 'attempts']);
            Route::middleware('permission:approve_results')->post('cbt-assessments/{cbtAssessment}/review-results', [CbtAssessmentController::class, 'reviewResults']);
            Route::middleware('permission:approve_results')->post('cbt-assessments/{cbtAssessment}/publish-results', [CbtAssessmentController::class, 'publishResults']);
            Route::middleware('permission:portal_student_access')->get('student/cbt-assessments', [CbtAssessmentController::class, 'availableForStudent']);
            Route::middleware('permission:portal_student_access')->post('student/cbt-assessments/{cbtAssessment}/start', [CbtAssessmentController::class, 'startForStudent']);
            Route::middleware('permission:portal_student_access')->post('student/cbt-attempts/{cbtAttempt}/answers', [CbtAssessmentController::class, 'answer']);
            Route::middleware('permission:portal_student_access')->post('student/cbt-attempts/{cbtAttempt}/submit', [CbtAssessmentController::class, 'submit']);
            Route::middleware('permission:portal_student_access')->get('student/cbt-attempts/{cbtAttempt}/result', [CbtAssessmentController::class, 'studentResult']);
            Route::middleware('permission:portal_student_access')->get('student/cbt-questions', [CbtQuestionController::class, 'studentQuestions']);
        });
    });
});
