/**
 * Canonical module registry derived from the DONO end-to-end architecture.
 *
 * Every dashboard module must have one stable key. `page` is the actual
 * frontend workspace, not a display alias. A module is not complete merely
 * because it appears in this registry; the matching backend route and
 * permission must also exist and be verified.
 */
export const ARCHITECTURE_MODULES = {
  dashboard: { key: "dashboard", label: "Dashboard", page: "dashboard", permission: "view_dashboard" },
  organizations: { key: "organizations", label: "Organizations", page: "organizations", permission: "manage_organizations", platform: true },
  schools: { key: "schools", label: "Schools", page: "schools", permission: "manage_schools", platform: true },
  subscriptions: { key: "subscriptions", label: "Subscriptions", page: "subscriptions", permission: "manage_subscriptions" },
  plans_features: { key: "plans_features", label: "Plans & Features", page: "subscriptions", permission: "manage_subscriptions", platform: true },
  payments_invoices: { key: "payments_invoices", label: "Payments & Invoices", page: "platform-payments", permission: "view_revenue", platform: true },
  system_settings: { key: "system_settings", label: "System Settings", page: "settings", permission: "manage_system_settings", platform: true },
  profile: { key: "profile", label: "My Profile", page: "profile", permission: "authenticated" },
  school_branding: { key: "school_branding", label: "School Branding & Report Card Design", page: "school-branding", permission: "manage_school_settings" },
  countries_currency: { key: "countries_currency", label: "Countries / Currency", page: "countries-currency", permission: "manage_system_settings", platform: true },
  email_sms_settings: { key: "email_sms_settings", label: "Email & SMS Settings", page: "email-sms-settings", permission: "manage_system_settings", platform: true },
  backups_logs: { key: "backups_logs", label: "Backups & Logs", page: "backups-logs", permission: "view_audit_logs", platform: true },
  system_health: { key: "system_health", label: "System Health", page: "system-health", permission: "view_audit_logs", platform: true },
  my_schools: { key: "my_schools", label: "My Schools", page: "schools", permission: "manage_schools" },
  create_school: { key: "create_school", label: "Create School", page: "add-school", permission: "manage_schools" },
  organization_profile: { key: "organization_profile", label: "Organization Profile", page: "organization-profile", permission: "manage_organizations" },
  users: { key: "users", label: "Users", page: "organization-users", permission: "manage_users" },
  staff_management: { key: "staff_management", label: "Staff Management", page: "staff", permission: "view_staff" },
  leadership_assignment: { key: "leadership_assignment", label: "Leadership Assignment", page: "role-invitations", permission: "assign_roles" },
  school_setup: { key: "school_setup", label: "Initial School Setup", page: "school-setup", permission: "manage_school_settings" },
  academic_sessions: { key: "academic_sessions", label: "Academic Sessions", page: "academic-sessions", permission: "manage_academic_sessions" },
  terms: { key: "terms", label: "Terms", page: "terms", permission: "manage_terms" },
  divisions: { key: "divisions", label: "Divisions", page: "divisions", permission: "manage_divisions" },
  classes: { key: "classes", label: "Classes", page: "classes", permission: "manage_classes" },
  streams: { key: "streams", label: "Streams", page: "streams", permission: "manage_streams" },
  subjects: { key: "subjects", label: "Subjects", page: "subjects", permission: "manage_subjects" },
  students: { key: "students", label: "Students", page: "students", permission: "view_students" },
  parents: { key: "parents", label: "Parents", page: "parents", permission: "manage_parents" },
  teachers: { key: "teachers", label: "Teachers", page: "teachers", permission: "view_staff" },
  attendance: { key: "attendance", label: "Attendance", page: "attendance", permission: "manage_attendance" },
  staff_attendance: { key: "staff_attendance", label: "Staff Attendance", page: "staff-attendance", permission: "manage_attendance" },
  examinations: { key: "examinations", label: "Examinations", page: "examinations", permission: "manage_examinations" },
  continuous_assessment: { key: "continuous_assessment", label: "Continuous Assessment", page: "result-entry", permission: "manage_exam_scores" },
  exam_scores: { key: "exam_scores", label: "Exam Scores", page: "result-entry", permission: "manage_exam_scores" },
  assessment_structures: { key: "assessment_structures", label: "Assessment Structure", page: "assessment-structures", permission: "manage_assessments" },
  results: { key: "results", label: "Results", page: "results", permission: "manage_results" },
  report_cards: { key: "report_cards", label: "Report Cards", page: "report-cards", permission: "manage_report_cards" },
  promotion: { key: "promotion", label: "Promotion", page: "promotions", permission: "manage_promotions" },
  timetable: { key: "timetable", label: "Timetable", page: "timetable", permission: "manage_timetable" },
  fees: { key: "fees", label: "Fees", page: "fees", permission: "manage_student_fees" },
  fees_payments: { key: "fees_payments", label: "Fees & Payments", page: "fees-payments", permission: "receive_payments" },
  expenses: { key: "expenses", label: "Expenses", page: "expenses", permission: "manage_budget" },
  payroll: { key: "payroll", label: "Payroll", page: "payroll", permission: "manage_payroll" },
  finance_reports: { key: "finance_reports", label: "Financial Reports", page: "financial-reports", permission: "view_finance_reports" },
  assignments: { key: "assignments", label: "Assignments", page: "assignments", permission: "view_assignments" },
  discipline: { key: "discipline", label: "Discipline / Behaviour", page: "discipline-cases", permission: "manage_discipline" },
  leave: { key: "leave", label: "Leave Management", page: "leave-requests", permission: "manage_staff" },
  safety: { key: "safety", label: "Health & Safety", page: "safety-incidents", permission: "manage_discipline" },
  inventory: { key: "inventory", label: "Inventory / Assets", page: "asset-register", permission: "manage_inventory" },
  events: { key: "events", label: "Events Management", page: "school-events", permission: "manage_events" },
  facilities: { key: "facilities", label: "Facilities Management", page: "school-facilities", permission: "manage_facilities" },
  library: { key: "library", label: "Library", page: "library-members", permission: "manage_library" },
  clinic: { key: "clinic", label: "Clinic", page: "clinic", permission: "manage_clinic" },
  hostel: { key: "hostel", label: "Hostel", page: "hostels", permission: "manage_hostel" },
  transport: { key: "transport", label: "Transport", page: "transport", permission: "manage_transport" },
  front_desk: { key: "front_desk", label: "Front Desk", page: "visitors", permission: "manage_front_desk" },
  communication: { key: "communication", label: "Communication", page: "communication", permission: "view_communication" },
  notices: { key: "notices", label: "School Notices", page: "notices", permission: "view_communication" },
  messages: { key: "messages", label: "Messages / Chat", page: "messages", permission: "view_communication" },
  cbt: { key: "cbt", label: "Question Bank (CBT)", page: "cbt", permission: "manage_cbt_questions" },
  cbt_assessments: { key: "cbt_assessments", label: "CBT Assessments", page: "cbt-assessments", permission: "manage_cbt_questions" },
  external_exams: { key: "external_exams", label: "External Exams (WAEC/NECO)", page: "external-exams", permission: "manage_examinations" },
  practicals: { key: "practicals", label: "Practicals", page: "practicals", permission: "manage_examinations" },
  graduation: { key: "graduation", label: "Graduation & Alumni", page: "graduation", permission: "manage_promotions" },
  parent_fees: { key: "parent_fees", label: "Fees & Payments", page: "fees-payments", permission: "portal_parent_access", portal: true },
  parent_timetable: { key: "parent_timetable", label: "Timetable", page: "timetable", permission: "portal_parent_access", portal: true },
  parent_leave: { key: "parent_leave", label: "Apply for Leave", page: "leave-application", permission: "portal_parent_access", portal: true },
  transport_tracking: { key: "transport_tracking", label: "Transport Tracking", page: "transport-tracking", permission: "portal_parent_access", portal: true },
  student_fees: { key: "student_fees", label: "Fees", page: "fees-payments", permission: "portal_student_access", portal: true },
  student_cbt: { key: "student_cbt", label: "CBT / Exams", page: "cbt", permission: "portal_student_access", portal: true },
};

export const moduleEntry = (key, overrides = {}) => ({
  ...ARCHITECTURE_MODULES[key],
  ...overrides,
});
