import { useEffect, useState } from "react";
import api from "../services/api";
import PageContainer from "../components/layout/PageContainer";
import PageHeader from "../components/layout/PageHeader";
import DataTable from "../components/tables/DataTable";
import Modal from "../components/modals/Modal";
import Button from "../components/forms/Button";
import { FormField, FormActions } from "../components/forms/FormField";
import Alert from "../components/feedback/Alert";

const emptyForm = { name: "", start_date: "", end_date: "", is_current: true };
const listFromResponse = (response) => { const value = response?.data?.data?.data ?? response?.data?.data ?? response?.data; return Array.isArray(value) ? value : []; };

export default function AcademicSessions() {
  const [sessions, setSessions] = useState([]); const [form, setForm] = useState(emptyForm); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const [showModal, setShowModal] = useState(false);
  const loadSessions = async () => { setLoading(true); setError(""); try { setSessions(listFromResponse(await api.get("/academic-sessions"))); } catch (err) { setSessions([]); setError(err.response?.data?.message || "Unable to load academic sessions."); } finally { setLoading(false); } };
  useEffect(() => { loadSessions(); }, []);
  const saveSession = async (event) => { event.preventDefault(); setSubmitting(true); setError(""); try { await api.post("/academic-sessions", form); setForm(emptyForm); setShowModal(false); await loadSessions(); } catch (err) { setError(err.response?.data?.message || "Unable to save academic session."); } finally { setSubmitting(false); } };
  const columns = [{ key: "name", label: "Session", render: (session) => <span className="font-semibold">{session.name}</span> }, { key: "start_date", label: "Start", render: (session) => session.start_date || "—" }, { key: "end_date", label: "End", render: (session) => session.end_date || "—" }, { key: "status", label: "Status", render: (session) => <span className={`status-badge ${session.is_current ? "status-badge-success" : "status-badge-muted"}`}>{session.is_current ? "Current" : "Archived"}</span> }];
  return <PageContainer><PageHeader title="Academic Sessions" subtitle="Create the school year or academic cycle before adding terms." action={<Button onClick={() => setShowModal(true)}>Add session</Button>} />{error && <Alert variant="error" action={<button type="button" onClick={loadSessions}>Retry</button>}>{error}</Alert>}<DataTable columns={columns} data={sessions} loading={loading} emptyTitle="No academic sessions yet" emptyMessage="Create the first session for this school." /><Modal open={showModal} title="Add academic session" description="A session contains the terms used for the school year." onClose={() => setShowModal(false)} footer={<FormActions sticky={false}><Button variant="secondary" onClick={() => setShowModal(false)}>Cancel</Button><Button type="submit" form="session-form" loading={submitting}>Save session</Button></FormActions>}><form id="session-form" onSubmit={saveSession} className="ui-form-grid"><FormField label="Session name" htmlFor="session-name" required><input id="session-name" name="name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="e.g. 2026/2027" required className="ui-form-control" /></FormField><div /><FormField label="Start date" htmlFor="session-start" required><input id="session-start" type="date" name="start_date" value={form.start_date} onChange={(event) => setForm({ ...form, start_date: event.target.value })} required className="ui-form-control" /></FormField><FormField label="End date" htmlFor="session-end" required><input id="session-end" type="date" name="end_date" value={form.end_date} onChange={(event) => setForm({ ...form, end_date: event.target.value })} required className="ui-form-control" /></FormField><label className="ui-form-field flex items-center gap-2"><input type="checkbox" name="is_current" checked={form.is_current} onChange={(event) => setForm({ ...form, is_current: event.target.checked })} /><span className="ui-form-label mb-0">Current academic session</span></label></form></Modal></PageContainer>;
}
