import { useEffect, useState } from "react";
import api from "../services/api";
import PageContainer from "../components/layout/PageContainer";
import PageHeader from "../components/layout/PageHeader";
import DataTable from "../components/tables/DataTable";
import Modal from "../components/modals/Modal";
import Button from "../components/forms/Button";
import { FormField, FormActions } from "../components/forms/FormField";
import Alert from "../components/feedback/Alert";

const emptyForm = { name: "", code: "", display_order: 1, is_active: true };
const listFromResponse = (response) => { const value = response?.data?.data?.data ?? response?.data?.data ?? response?.data; return Array.isArray(value) ? value : []; };

export default function Divisions() {
  const [divisions, setDivisions] = useState([]); const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState(null); const [showModal, setShowModal] = useState(false); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(""); const [formError, setFormError] = useState("");
  const loadDivisions = async () => { setLoading(true); setError(""); try { setDivisions(listFromResponse(await api.get("/divisions"))); } catch (err) { setDivisions([]); setError(err.response?.data?.message || "Unable to load divisions."); } finally { setLoading(false); } };
  useEffect(() => { loadDivisions(); }, []);
  const openModal = (division = null) => { setEditingId(division?.id || null); setForm(division ? { name: division.name || "", code: division.code || "", display_order: division.display_order || 1, is_active: division.is_active ?? true } : emptyForm); setFormError(""); setShowModal(true); };
  const saveDivision = async (event) => { event.preventDefault(); setSubmitting(true); setFormError(""); try { if (editingId) await api.put(`/divisions/${editingId}`, form); else await api.post("/divisions", form); setShowModal(false); setForm(emptyForm); await loadDivisions(); } catch (err) { const validationErrors = err.response?.data?.errors; setFormError(validationErrors ? Object.values(validationErrors).flat().join(" ") : (err.response?.data?.message || "Unable to save division.")); } finally { setSubmitting(false); } };
  const deleteDivision = async (division) => { if (!window.confirm(`Delete ${division.name}?`)) return; try { await api.delete(`/divisions/${division.id}`); await loadDivisions(); } catch (err) { setError(err.response?.data?.message || "Unable to delete division."); } };
  const columns = [{ key: "name", label: "Name", render: (division) => <span className="font-semibold">{division.name}</span> }, { key: "code", label: "Code", render: (division) => division.code || "—" }, { key: "display_order", label: "Order", render: (division) => division.display_order || "—" }, { key: "status", label: "Status", render: (division) => <span className={`status-badge ${division.is_active ? "status-badge-success" : "status-badge-muted"}`}>{division.is_active ? "Active" : "Inactive"}</span> }, { key: "actions", label: "Actions", align: "right", render: (division) => <div className="table-actions"><Button size="sm" variant="ghost" onClick={() => openModal(division)}>Edit</Button><Button size="sm" variant="danger" onClick={() => deleteDivision(division)}>Delete</Button></div> }];
  return <PageContainer><PageHeader title="Divisions" subtitle="Create broad school sections before defining classes and streams." action={<Button onClick={() => openModal()}>Add division</Button>} />{error && <Alert variant="error" action={<button type="button" onClick={loadDivisions}>Retry</button>}>{error}</Alert>}<DataTable columns={columns} data={divisions} loading={loading} emptyTitle="No divisions yet" emptyMessage="Create divisions such as Nursery, Primary, or Secondary." /><Modal open={showModal} title={editingId ? "Edit division" : "Add division"} onClose={() => setShowModal(false)} footer={<FormActions sticky={false}><Button variant="secondary" onClick={() => setShowModal(false)}>Cancel</Button><Button type="submit" form="division-form" loading={submitting}>Save division</Button></FormActions>}><form id="division-form" onSubmit={saveDivision} className="ui-form-grid">{formError && <div className="ui-form-full"><Alert variant="error">{formError}</Alert></div>}<FormField label="Division name" htmlFor="division-name" required><input id="division-name" name="name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="e.g. Primary" required className="ui-form-control" /></FormField><FormField label="Code" htmlFor="division-code" hint="Optional short code"><input id="division-code" name="code" value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} placeholder="e.g. PRI" className="ui-form-control" /></FormField><FormField label="Display order" htmlFor="division-order" required><input id="division-order" name="display_order" type="number" min="1" value={form.display_order} onChange={(event) => setForm({ ...form, display_order: event.target.value })} required className="ui-form-control" /></FormField><label className="ui-form-field flex items-center gap-2"><input type="checkbox" name="is_active" checked={form.is_active} onChange={(event) => setForm({ ...form, is_active: event.target.checked })} /><span className="ui-form-label mb-0">Active division</span></label></form></Modal></PageContainer>;
}
