import { useEffect, useState } from "react";
import api from "../services/api";
import PageContainer from "../components/layout/PageContainer";
import PageHeader from "../components/layout/PageHeader";
import LoadingSpinner from "../components/feedback/LoadingSpinner";
import EmptyState from "../components/feedback/EmptyState";

const initial = { staff_id: "", pay_period: "", gross_amount: "", deductions: "", status: "Draft" };
const rows = (response) => { const value = response?.data?.data ?? response?.data ?? []; if (Array.isArray(value)) return value; if (Array.isArray(value?.data)) return value.data; return []; };

export default function Payroll() {
  const [items, setItems] = useState([]); const [form, setForm] = useState(initial); const [showForm, setShowForm] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { try { setLoading(true); setError(""); const response = await api.get("/payroll"); setItems(rows(response)); } catch (err) { setItems([]); setError(err.response?.data?.message || "Unable to load payroll."); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function submit(event) { event.preventDefault(); try { setSaving(true); setError(""); setMessage(""); await api.post("/payroll", { ...form, staff_id: Number(form.staff_id), gross_amount: Number(form.gross_amount), deductions: Number(form.deductions || 0) }); setForm(initial); setShowForm(false); setMessage("Payroll entry created."); await load(); } catch (err) { const errors = err.response?.data?.errors; setError(errors ? Object.values(errors)?.[0]?.[0] : err.response?.data?.message || "Unable to save payroll entry."); } finally { setSaving(false); } }
  return <PageContainer><PageHeader title="Payroll" subtitle="Prepare and track school staff payroll." action={<button type="button" onClick={() => setShowForm((value) => !value)} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">{showForm ? "Close" : "Add payroll"}</button>} />{error && <div role="alert" className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error} <button type="button" onClick={load} className="ml-2 underline">Retry</button></div>}{message && <div role="status" className="mb-4 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}{showForm && <form onSubmit={submit} className="mb-6 grid gap-3 rounded-xl border bg-white p-4 shadow-sm sm:grid-cols-2"><input required placeholder="Staff ID" inputMode="numeric" value={form.staff_id} onChange={(event) => setForm({ ...form, staff_id: event.target.value })} className="rounded-lg border p-2" /><input required type="month" value={form.pay_period} onChange={(event) => setForm({ ...form, pay_period: event.target.value })} className="rounded-lg border p-2" /><input required type="number" min="0" placeholder="Gross amount" value={form.gross_amount} onChange={(event) => setForm({ ...form, gross_amount: event.target.value })} className="rounded-lg border p-2" /><input type="number" min="0" placeholder="Deductions" value={form.deductions} onChange={(event) => setForm({ ...form, deductions: event.target.value })} className="rounded-lg border p-2" /><button type="submit" disabled={saving} className="rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white disabled:opacity-60 sm:col-span-2">{saving ? "Saving..." : "Save payroll"}</button></form>}{loading ? <LoadingSpinner /> : items.length === 0 ? <EmptyState title="No payroll entries" message="Create the first payroll entry for this school." /> : <div className="overflow-x-auto rounded-xl border bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead><tr className="border-b bg-slate-50"><th className="p-3">Staff</th><th className="p-3">Period</th><th className="p-3">Gross</th><th className="p-3">Net</th><th className="p-3">Status</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b"><td className="p-3">{item.staff?.full_name || item.staff?.staff_number || item.staff_id}</td><td className="p-3">{item.pay_period}</td><td className="p-3">{item.gross_amount}</td><td className="p-3">{item.net_amount}</td><td className="p-3">{item.status}</td></tr>)}</tbody></table></div>}</PageContainer>;
}
