import { useEffect, useState } from "react";
import api from "../services/api";
import PageContainer from "../components/layout/PageContainer";
import PageHeader from "../components/layout/PageHeader";
import SectionCard from "../components/layout/SectionCard";
import DataTable from "../components/tables/DataTable";
import Modal from "../components/modals/Modal";
import Button from "../components/forms/Button";
import { FormField, FormActions } from "../components/forms/FormField";
import Alert from "../components/feedback/Alert";
import { useAuth } from "../context/AuthContext";

const emptyForm = { class_id: "", name: "", code: "", display_order: 1, is_active: true };
const listFromResponse = (response) => { const value = response?.data?.data?.data ?? response?.data?.data ?? response?.data; return Array.isArray(value) ? value : []; };

export default function Streams() {
  const { permissions = [] } = useAuth();
  const canManageStreams = permissions.includes("manage_streams");
  const [streams, setStreams] = useState([]); const [classes, setClasses] = useState([]); const [form, setForm] = useState(emptyForm); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const [showModal, setShowModal] = useState(false);
  const loadData = async () => { setLoading(true); setError(""); try { const [streamsResponse, classesResponse] = await Promise.all([api.get("/streams"), api.get("/classes")]); setStreams(listFromResponse(streamsResponse)); setClasses(listFromResponse(classesResponse)); } catch (err) { setStreams([]); setClasses([]); setError(err.response?.data?.message || "Unable to load streams and classes."); } finally { setLoading(false); } };
  useEffect(() => { loadData(); }, []);
  const saveStream = async (event) => {
    if (!canManageStreams) return; event.preventDefault(); setSubmitting(true); setError(""); try { await api.post("/streams", form); setForm(emptyForm); setShowModal(false); await loadData(); } catch (err) { setError(err.response?.data?.message || "Unable to save stream."); } finally { setSubmitting(false); } };
  const columns = [{ key: "name", label: "Stream", render: (stream) => <span className="font-semibold">{stream.name}</span> }, { key: "class", label: "Class", render: (stream) => stream.class?.name || classes.find((item) => String(item.id) === String(stream.class_id))?.name || "—" }, { key: "code", label: "Code", render: (stream) => stream.code || "—" }, { key: "status", label: "Status", render: (stream) => <span className={`status-badge ${stream.is_active ? "status-badge-success" : "status-badge-muted"}`}>{stream.is_active ? "Active" : "Inactive"}</span> }];
  return <PageContainer><PageHeader title="Streams" subtitle={canManageStreams ? "Create streams under classes that already belong to your school." : "View the streams configured by authorized school administrators."} action={canManageStreams ? <Button onClick={() => setShowModal(true)}>Add stream</Button> : null} />{error && <Alert variant="error" action={<button type="button" onClick={loadData}>Retry</button>}>{error}</Alert>}<SectionCard title="Stream directory" subtitle={`${streams.length} streams`}><DataTable columns={columns} data={streams} loading={loading} emptyTitle="No streams yet" emptyMessage="Create a stream after adding classes." /></SectionCard>{canManageStreams && <Modal open={showModal} title="Add stream" description="Assign the stream to an existing class." onClose={() => setShowModal(false)} footer={<FormActions sticky={false}><Button variant="secondary" onClick={() => setShowModal(false)}>Cancel</Button><Button type="submit" form="stream-form" loading={submitting}>Save stream</Button></FormActions>}><form id="stream-form" onSubmit={saveStream} className="ui-form-grid"><FormField label="Class" htmlFor="stream-class" required><select id="stream-class" name="class_id" value={form.class_id} onChange={(event) => setForm({ ...form, class_id: event.target.value })} required className="ui-form-control"><option value="">Select class</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></FormField><FormField label="Stream name" htmlFor="stream-name" required><input id="stream-name" name="name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="e.g. A or Gold" required className="ui-form-control" /></FormField><FormField label="Code" htmlFor="stream-code"><input id="stream-code" name="code" value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} placeholder="Optional" className="ui-form-control" /></FormField><FormField label="Display order" htmlFor="stream-order"><input id="stream-order" type="number" min="1" name="display_order" value={form.display_order} onChange={(event) => setForm({ ...form, display_order: event.target.value })} className="ui-form-control" /></FormField><label className="ui-form-field flex items-center gap-2"><input type="checkbox" name="is_active" checked={form.is_active} onChange={(event) => setForm({ ...form, is_active: event.target.checked })} /><span className="ui-form-label mb-0">Active stream</span></label></form></Modal>}</PageContainer>;
}
