import { useEffect, useState } from "react";
import api from "../services/api";
import PageContainer from "../components/layout/PageContainer";
import PageHeader from "../components/layout/PageHeader";
import DataTable from "../components/tables/DataTable";
import Modal from "../components/modals/Modal";
import Button from "../components/forms/Button";
import { FormField, FormActions } from "../components/forms/FormField";
import Alert from "../components/feedback/Alert";
import { useAuth } from "../context/AuthContext";

const emptyForm = { name: "", code: "", category: "Core", division_id: "", pass_mark: 40, maximum_mark: 100, is_active: true, description: "" };
const listFromResponse = (response) => { const value = response?.data?.data?.data ?? response?.data?.data ?? response?.data; return Array.isArray(value) ? value : []; };

export default function Subjects({ teacherOnly = false }) {
  const { permissions = [] } = useAuth();
  const canManageSubjects = !teacherOnly && permissions.includes("manage_subjects");
  const [subjects, setSubjects] = useState([]); const [divisions, setDivisions] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [formError, setFormError] = useState(""); const [showModal, setShowModal] = useState(false); const [submitting, setSubmitting] = useState(false); const [editingId, setEditingId] = useState(null); const [form, setForm] = useState(emptyForm);
  const loadData = async () => { setLoading(true); setError(""); try { if (teacherOnly) { const response = await api.get("/teacher/dashboard"); const payload = response?.data; setSubjects(Array.isArray(payload?.my_subjects) ? payload.my_subjects : []); setDivisions([]); return; } const [subjectsResponse, divisionsResponse] = await Promise.all([api.get("/subjects"), api.get("/divisions")]); setSubjects(listFromResponse(subjectsResponse)); setDivisions(listFromResponse(divisionsResponse)); } catch (err) { setError(err.response?.data?.message || "Unable to load subjects and divisions."); setSubjects([]); setDivisions([]); } finally { setLoading(false); } };
  useEffect(() => { loadData(); }, []);
  const openModal = (subject = null) => { if (!canManageSubjects) return; setFormError(""); setEditingId(subject?.id || null); setForm(subject ? { name: subject.name || "", code: subject.code || "", category: subject.category || "Core", division_id: subject.division_id || subject.division?.id || "", pass_mark: subject.pass_mark ?? 40, maximum_mark: subject.maximum_mark ?? 100, is_active: subject.is_active ?? true, description: subject.description || "" } : { ...emptyForm, division_id: divisions[0]?.id || "" }); setShowModal(true); };
  const handleChange = (event) => { const { name, value, checked, type } = event.target; setForm((current) => ({ ...current, [name]: type === "checkbox" ? checked : value })); };
  const saveSubject = async (event) => { event.preventDefault(); setSubmitting(true); setFormError(""); try { if (editingId) await api.put(`/subjects/${editingId}`, form); else await api.post("/subjects", form); setShowModal(false); setForm(emptyForm); await loadData(); } catch (err) { const validationErrors = err.response?.data?.errors; setFormError(validationErrors ? Object.values(validationErrors).flat().join(" ") : (err.response?.data?.message || "Unable to save subject.")); } finally { setSubmitting(false); } };
  const deleteSubject = async (subject) => { if (!window.confirm(`Delete ${subject.name}?`)) return; try { await api.delete(`/subjects/${subject.id}`); await loadData(); } catch (err) { setError(err.response?.data?.message || "Unable to delete subject."); } };
  const columns = teacherOnly ? [
    { key: "name", label: "Assigned subject", render: (subject) => <span className="font-semibold">{subject.name || "Subject"}</span> },
    { key: "class", label: "Class", render: (subject) => subject.class || "—" },
    { key: "assignment", label: "Assignment", render: () => <span className="status-badge status-badge-muted">Read-only</span> },
  ] : [
    { key: "name", label: "Name", render: (subject) => <span className="font-semibold">{subject.name}</span> },
    { key: "division", label: "Division", render: (subject) => subject.division?.name || divisions.find((division) => String(division.id) === String(subject.division_id))?.name || "—" },
    { key: "code", label: "Code", render: (subject) => subject.code || "—" },
    { key: "marks", label: "Pass / Max", render: (subject) => `${subject.pass_mark ?? 40} / ${subject.maximum_mark ?? 100}` },
    { key: "status", label: "Status", render: (subject) => <span className={`status-badge ${subject.is_active ? "status-badge-success" : "status-badge-muted"}`}>{subject.is_active ? "Active" : "Inactive"}</span> },
    ...(canManageSubjects ? [{ key: "actions", label: "Actions", align: "right", render: (subject) => <div className="table-actions"><Button size="sm" variant="ghost" onClick={() => openModal(subject)}>Edit</Button><Button size="sm" variant="danger" onClick={() => deleteSubject(subject)}>Delete</Button></div> }] : []),
  ];
  return <PageContainer><PageHeader title="Subjects" subtitle={canManageSubjects ? "Define curriculum subjects after divisions, classes, and streams are ready." : "View the subjects configured by authorized school administrators."} action={canManageSubjects ? <Button onClick={() => openModal()}>Add subject</Button> : null} />{error && <Alert variant="error" action={<button type="button" onClick={loadData}>Retry</button>}>{error}</Alert>}<DataTable columns={columns} data={subjects} loading={loading} emptyTitle="No subjects yet" emptyMessage="Create the first subject for this school." />{canManageSubjects && <Modal open={showModal} title={editingId ? "Edit subject" : "Add subject"} onClose={() => setShowModal(false)} footer={<FormActions sticky={false}><Button variant="secondary" onClick={() => setShowModal(false)}>Cancel</Button><Button type="submit" form="subject-form" loading={submitting}>Save subject</Button></FormActions>}><form id="subject-form" onSubmit={saveSubject} className="ui-form-grid">{formError && <div className="ui-form-full"><Alert variant="error">{formError}</Alert></div>}<FormField label="Subject name" htmlFor="subject-name" required><input id="subject-name" name="name" value={form.name} onChange={handleChange} required className="ui-form-control" /></FormField><FormField label="Code" htmlFor="subject-code"><input id="subject-code" name="code" value={form.code} onChange={handleChange} className="ui-form-control" /></FormField><FormField label="Category" htmlFor="subject-category"><select id="subject-category" name="category" value={form.category} onChange={handleChange} className="ui-form-control"><option>Core</option><option>Elective</option><option>Vocational</option><option>Trade</option></select></FormField><FormField label="Division" htmlFor="subject-division" required><select id="subject-division" name="division_id" value={form.division_id} onChange={handleChange} required className="ui-form-control"><option value="">Select division</option>{divisions.map((division) => <option key={division.id} value={division.id}>{division.name}</option>)}</select></FormField><FormField label="Pass mark" htmlFor="subject-pass"><input id="subject-pass" type="number" min="0" name="pass_mark" value={form.pass_mark} onChange={handleChange} className="ui-form-control" /></FormField><FormField label="Maximum mark" htmlFor="subject-max"><input id="subject-max" type="number" min="1" name="maximum_mark" value={form.maximum_mark} onChange={handleChange} className="ui-form-control" /></FormField><FormField label="Description" htmlFor="subject-description"><textarea id="subject-description" name="description" value={form.description} onChange={handleChange} className="ui-form-control" /></FormField><label className="ui-form-field flex items-center gap-2"><input type="checkbox" name="is_active" checked={form.is_active} onChange={handleChange} /><span className="ui-form-label mb-0">Active subject</span></label></form></Modal>}</PageContainer>;
}
