import { useEffect, useState } from "react";
import api from "../services/api";
import PageContainer from "../components/layout/PageContainer";
import PageHeader from "../components/layout/PageHeader";
import DataTable from "../components/tables/DataTable";
import Modal from "../components/modals/Modal";
import Button from "../components/forms/Button";
import { FormField, FormActions } from "../components/forms/FormField";
import Alert from "../components/feedback/Alert";

const emptyForm = { academic_session_id: "", name: "", start_date: "", end_date: "", is_current: true, status: "active" };
const listFromResponse = (response) => { const value = response?.data?.data?.data ?? response?.data?.data ?? response?.data; return Array.isArray(value) ? value : []; };

export default function Terms() {
  const [terms, setTerms] = useState([]); const [sessions, setSessions] = useState([]); const [form, setForm] = useState(emptyForm); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const [showModal, setShowModal] = useState(false);
  const loadData = async () => { setLoading(true); setError(""); try { const [termsResponse, sessionsResponse] = await Promise.all([api.get("/terms"), api.get("/academic-sessions")]); setTerms(listFromResponse(termsResponse)); setSessions(listFromResponse(sessionsResponse)); } catch (err) { setError(err.response?.data?.message || "Unable to load terms and academic sessions."); setTerms([]); setSessions([]); } finally { setLoading(false); } };
  useEffect(() => { loadData(); }, []);
  const saveTerm = async (event) => { event.preventDefault(); setSubmitting(true); setError(""); try { await api.post("/terms", form); setForm(emptyForm); setShowModal(false); await loadData(); } catch (err) { setError(err.response?.data?.message || "Unable to save term."); } finally { setSubmitting(false); } };
  const columns = [{ key: "session", label: "Session", render: (term) => term.academic_session?.name || "—" }, { key: "name", label: "Term", render: (term) => <span className="font-semibold">{term.name}</span> }, { key: "start_date", label: "Start", render: (term) => term.start_date || "—" }, { key: "end_date", label: "End", render: (term) => term.end_date || "—" }, { key: "status", label: "Status", render: (term) => <span className={`status-badge ${term.is_current ? "status-badge-success" : "status-badge-muted"}`}>{term.is_current ? "Current" : term.status || "Inactive"}</span> }];
  return <PageContainer><PageHeader title="Terms" subtitle="Create the terms that belong to an academic session." action={<Button onClick={() => setShowModal(true)}>Add term</Button>} />{error && <Alert variant="error" action={<button type="button" onClick={loadData}>Retry</button>}>{error}</Alert>}<DataTable columns={columns} data={terms} loading={loading} emptyTitle="No terms yet" emptyMessage="Create a term after adding an academic session." /><Modal open={showModal} title="Add term" description="Set the dates and current status for this term." onClose={() => setShowModal(false)} footer={<FormActions sticky={false}><Button variant="secondary" onClick={() => setShowModal(false)}>Cancel</Button><Button type="submit" form="term-form" loading={submitting}>Save term</Button></FormActions>}><form id="term-form" onSubmit={saveTerm} className="ui-form-grid"><FormField label="Academic session" htmlFor="term-session" required><select id="term-session" name="academic_session_id" value={form.academic_session_id} onChange={(event) => setForm({ ...form, academic_session_id: event.target.value })} required className="ui-form-control"><option value="">Select academic session</option>{sessions.map((session) => <option key={session.id} value={session.id}>{session.name}</option>)}</select></FormField><FormField label="Term" htmlFor="term-name" required><select id="term-name" name="name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required className="ui-form-control"><option value="">Select term</option><option>First Term</option><option>Second Term</option><option>Third Term</option></select></FormField><FormField label="Start date" htmlFor="term-start" required><input id="term-start" type="date" name="start_date" value={form.start_date} onChange={(event) => setForm({ ...form, start_date: event.target.value })} required className="ui-form-control" /></FormField><FormField label="End date" htmlFor="term-end" required><input id="term-end" type="date" name="end_date" value={form.end_date} onChange={(event) => setForm({ ...form, end_date: event.target.value })} required className="ui-form-control" /></FormField><FormField label="Status" htmlFor="term-status"><select id="term-status" name="status" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })} className="ui-form-control"><option value="active">Active</option><option value="closed">Closed</option></select></FormField><label className="ui-form-field flex items-center gap-2"><input type="checkbox" name="is_current" checked={form.is_current} onChange={(event) => setForm({ ...form, is_current: event.target.checked })} /><span className="ui-form-label mb-0">Current term</span></label></form></Modal></PageContainer>;
}
